# Generated by Django 3.2 on 2021-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='name',
        ),
    ]
